<?php

// =====================================================================

// !!  路由文件由 owl-admin 自动生成，请不要手动修改。

// !!  Route file auto generated by owl-admin, don't modify it manually.

// =====================================================================

use Slowlyo\OwlAdmin\Admin;
use Illuminate\Routing\Router;
use Illuminate\Support\Facades\Route;

Route::group([
    'domain'     => Admin::config('admin.route.domain'),
    'prefix'     => Admin::config('admin.route.prefix'),
    'middleware' => Admin::config('admin.route.middleware'),
], function (Router $router) {
    // Email配置
    $router->resource('email/mail_conf', \App\Admin\Controllers\Email\MailConfController::class);
    // Email用户
    $router->resource('email/mail_users', \App\Admin\Controllers\Email\MailUserController::class);
    // Email邮件
    $router->resource('email/mail_order', \App\Admin\Controllers\Email\MailOrderController::class);
    // Email发送邮件用户
    $router->resource('email/mail_send_user', \App\Admin\Controllers\Email\MailSendUserController::class);
    // 汇率表
    $router->resource('email/currency_exchange_rates', \App\Admin\Controllers\Email\CurrencyExchangeRateController::class);
    // mail
    $router->get('public/emailGetConfig', [\Slowlyo\OwlAdmin\Controllers\AdminApiController::class, 'index']);

});